

import localFont from "next/font/local";
import "./globals.css";
import Navigation from "./Components/Navigation";


import FinanceContextProvider from './lib/store/finance-context';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Finance Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FinanceContextProvider>
         <Navigation />
         {children}
        </FinanceContextProvider>
      </body>
    </html>
  );
}
